defaults:
  - data: humanml3d
  - defaults
  - _self_

device: cuda

annotations_filename: annotations_all.json
output_folder_name_token: token_embeddings_all
output_folder_name_sent: sent_embeddings_all
